# Generated by Django 5.1.1 on 2024-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('team', 'day')},
        ),
    ]
