# Generated by Django 5.1.1 on 2024-10-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
